name: Run tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

jobs:
  test-with-otio:
    env:
      plugin_name: "mlt_xml"

    name: "Test in OpenTimelineIO"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8]
        otio-versions: [0.12.1, 0.13.0]

    steps:
    - name: Setup otio version
      with:
        otio-version: ${{ matrix.otio-version }}

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov -V OpenTimelineIO==${{ matrix.otio-version }}

    - name: Install Plugin
      run: |
        pip install -e .

    - name: Lint with flake8
      run: |
        flake8 --show-source --statistics

    - name: Test with pytest
      run: |
        pytest

    - name: Check registration of plugin
      run: |
        [[ ! -z $(otiopluginfo mlt_xml | grep ${{ env.plugin_name }}) ]]
